from habutax.form import AutoNumber


from enum import auto, unique


@unique
class Jurisdiction(AutoNumber):
    # US Federal
    US = auto()
    # US state
    AK = auto()
    AL = auto()
    AR = auto()
    AZ = auto()
    CA = auto()
    CO = auto()
    CT = auto()
    DC = auto()
    DE = auto()
    FL = auto()
    GA = auto()
    HI = auto()
    IA = auto()
    ID = auto()
    IL = auto()
    IN = auto()
    KS = auto()
    KY = auto()
    LA = auto()
    MA = auto()
    MD = auto()
    ME = auto()
    MI = auto()
    MN = auto()
    MO = auto()
    MS = auto()
    MT = auto()
    NC = auto()
    ND = auto()
    NE = auto()
    NH = auto()
    NJ = auto()
    NM = auto()
    NV = auto()
    NY = auto()
    OH = auto()
    OK = auto()
    OR = auto()
    PA = auto()
    PR = auto()
    RI = auto()
    SC = auto()
    SD = auto()
    TN = auto()
    TX = auto()
    UT = auto()
    VA = auto()
    VT = auto()
    WA = auto()
    WI = auto()
    WV = auto()
    WY = auto()
